name: PR Example app

on: pull_request

jobs:
  tests:
    name: Build Example app
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Cache Pods
      uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Example/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
#    - name: Cache SPM
#      uses: actions/cache@v1
#      with:
#        path: .build
#        key: ${{ runner.os }}-gems-${{ hashFiles('**/Example/Gemfile.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-gems-
    - name: Build and run example project
      run: ./build.sh example
