name: Build Framework

on: pull_request

jobs:
  tests:
    name: Build Framework
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Build framework
      run: ./GitHubActions/build.sh framework
