name: Build Framework

on: pull_request

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  tests:
    name: Build Framework
    runs-on: macos-13
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v3
    - name: Build framework
      run: make framework
