name: Danger

on: 
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  danger:
    name: Run Danger    
    runs-on: macos-12
    env: 
       DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Resolve SwiftPM dependencies
      run: rm -rf ".build" && swift package clean && swift package resolve
    - name: Run build script
      run: gem install bundler && bundle install && bundle exec danger --fail-on-errors=true
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
