name: PR Danger

on: pull_request

jobs:
  danger:
    name: Run Danger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Run build script
      command: gem install bundler && bundle install && bundle exec danger --fail-on-errors=true
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
